version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/New_York"
    # This is the KEY setting for transitive dependencies
    update-subdependencies: true
    open-pull-requests-limit: 10
    auto-merge:
      enabled: true
      update-types:
        - "security:patch"
        - "security:minor"
    groups:
      netty:
        patterns:
          - "io.netty*"
      security-updates:
        update-types:
          - "patch"
          - "minor"
