# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle" # For Java/Kotlin projects using Gradle
    directory: "/" # Location of package manifests (build.gradle/build.gradle.kts)
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/New_York"
    # Enable security updates
    open-pull-requests-limit: 10
    # Include transitive dependencies
    update-subdependencies: true
    # Automatically merge minor and patch updates
    auto-merge:
      enabled: true
      update-types:
        - "security:patch"
        - "security:minor"
    # Group updates to reduce PR noise
    groups:
      netty:
        patterns:
          - "io.netty*"
      security-updates:
        update-types:
          - "security"
